<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>Icon.ico</ApplicationIcon>
		
		<!-- Version Information -->
		<Version>2.0.0</Version>
		<AssemblyVersion>2.0.0.0</AssemblyVersion>
		<FileVersion>2.0.0.0</FileVersion>
		<InformationalVersion>2.0.0</InformationalVersion>
		<AssemblyName>MirrorsEdgeMapManager</AssemblyName>
		<Product>MirrorsEdgeMapManager</Product>
		<AssemblyTitle>MirrorsEdgeMapManager</AssemblyTitle>
		<Company>MirrorsEdgeMapManager</Company>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="System.Text.Json" Version="9.0.0" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="ConfigTemplates\DefaultEngine.ini" />
		<EmbeddedResource Include="ConfigTemplates\DefaultGame.ini" />
		<EmbeddedResource Include="ConfigTemplates\TdGameUI.int" />
	</ItemGroup>

</Project>

