[TdGame.UIDataStore_TdGameData]
+ElementProviderTypes=(ProviderTag="TdMaps",ProviderClassName="TdGame.UIDataProvider_TdMaps")

[Fp.UIDataStore_TdCustomMapsGameData]
+ElementProviderTypes=(ProviderTag="TdMaps",ProviderClassName="TdGame.UIDataProvider_TdMaps")

;MEMM custom data stores:
[Fp.UIDataStore_TdCustomMapsTimeTrialData]
+ElementProviderTypes=(ProviderTag="TdTimeTrialStretches",ProviderClassName="TdGame.UIDataProvider_TdTimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdLevelRaceStretches",ProviderClassName="TdGame.UIDataProvider_TdLevelRaceStretch")
WeeklyGhostCutoffRank=500
MonthlyGhostCutoffRank=500
+ElementProviderTypes=(ProviderTag="TdCustomTimeTrialStretches",ProviderClassName="CustomStretches.UIDataProvider_TdCustomTimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdCustomLevelRaceStretches",ProviderClassName="CustomStretches.UIDataProvider_TdCustomLevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdCustomSceneStretch",ProviderClassName="CustomStretches.UIDataProvider_TdCustomSceneStretch")
+ElementProviderTypes=(ProviderTag="TdScene1NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene1NewGame")
+ElementProviderTypes=(ProviderTag="TdScene1ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene1ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene1TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene1TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene1LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene1LevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdScene2NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene2NewGame")
+ElementProviderTypes=(ProviderTag="TdScene2ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene2ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene2TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene2TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene2LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene2LevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdScene3NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene3NewGame")
+ElementProviderTypes=(ProviderTag="TdScene3ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene3ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene3TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene3TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene3LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene3LevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdScene4NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene4NewGame")
+ElementProviderTypes=(ProviderTag="TdScene4ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene4ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene4TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene4TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene4LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene4LevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdScene5NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene5NewGame")
+ElementProviderTypes=(ProviderTag="TdScene5ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene5ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene5TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene5TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene5LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene5LevelRaceStretch")

[Fp.UIDataStore_TdCustomMapsRaceData]
+ElementProviderTypes=(ProviderTag="TdTimeTrialStretches",ProviderClassName="TdGame.UIDataProvider_TdTimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdLevelRaceStretches",ProviderClassName="TdGame.UIDataProvider_TdLevelRaceStretch")
WeeklyGhostCutoffRank=500
MonthlyGhostCutoffRank=500
+ElementProviderTypes=(ProviderTag="TdCustomTimeTrialStretches",ProviderClassName="CustomStretches.UIDataProvider_TdCustomTimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdCustomLevelRaceStretches",ProviderClassName="CustomStretches.UIDataProvider_TdCustomLevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdCustomSceneStretch",ProviderClassName="CustomStretches.UIDataProvider_TdCustomSceneStretch")
+ElementProviderTypes=(ProviderTag="TdScene1NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene1NewGame")
+ElementProviderTypes=(ProviderTag="TdScene1ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene1ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene1TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene1TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene1LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene1LevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdScene2NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene2NewGame")
+ElementProviderTypes=(ProviderTag="TdScene2ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene2ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene2TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene2TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene2LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene2LevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdScene3NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene3NewGame")
+ElementProviderTypes=(ProviderTag="TdScene3ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene3ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene3TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene3TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene3LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene3LevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdScene4NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene4NewGame")
+ElementProviderTypes=(ProviderTag="TdScene4ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene4ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene4TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene4TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene4LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene4LevelRaceStretch")
+ElementProviderTypes=(ProviderTag="TdScene5NewGame",ProviderClassName="CustomStretches.UIDataProvider_TdScene5NewGame")
+ElementProviderTypes=(ProviderTag="TdScene5ChapterSelectStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene5ChapterSelectStretch")
+ElementProviderTypes=(ProviderTag="TdScene5TimeTrialStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene5TimeTrialStretch")
+ElementProviderTypes=(ProviderTag="TdScene5LevelRaceStretch",ProviderClassName="CustomStretches.UIDataProvider_TdScene5LevelRaceStretch")

[TdGame.UIDataStore_TdCustomTabData]
+ElementProviderTypes=(ProviderTag="TdCustomSceneStretches",ProviderClassName="CustomStretches.UIDataProvider_TdCustomSceneStretch")